In [1]:
import pandas as pd

In [2]:
import os

os.getcwd()

'C:\\Users\\ASUS\\Pandas'

In [14]:
os.listdir()

['.ipynb_checkpoints',
 'customer_behavior.ipynb',
 'customer_shopping_behavior.csv',
 'practice.ipynb',
 'Superstore.csv.xlsx',
 'superstore.ipynb',
 'Superstore1.csv',
 'test1_data.csv']

In [17]:
df = pd.read_csv("Superstore1.csv", encoding="latin1")

In [18]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub/Category,Product Name,Sales,Quantity,Discount,Profit,Month
0,1,CA/2016/152156,08-11-2016,11-11-2016,Second Class,CG/12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR/BO/10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91,November
1,2,CA/2016/152156,08-11-2016,11-11-2016,Second Class,CG/12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR/CH/10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58,November
2,3,CA/2016/138688,12-06-2016,16-06-2016,Second Class,DV/13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF/LA/10000240,Office Supplies,Labels,Self/Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87,June
3,4,US/2015/108966,11-10-2015,18-10-2015,Standard Class,SO/20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR/TA/10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,383.03,October
4,5,US/2015/108966,11-10-2015,18-10-2015,Standard Class,SO/20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF/ST/10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52,October

In [19]:
print(excel_file.sheet_names)

['Sheet2']

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub/Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Month          9994 non-null   str
dtypes: float64(3), int64(3), str(16)
memory usage: 1.7 MB

In [21]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858022,3.789574,0.156203,59.902092
std,2885.163629,32063.693350,623.245131,2.225110,0.206452,228.277303
min,1.000000,1040.000000,0.440000,1.000000,0.000000,0.000000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,5.370000
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,13.965000
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,43.150000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.980000

In [22]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub/Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
Month            0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [33]:
#converting dates
df["Order Date"] = pd.to_datetime(df["Order Date"])

df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [34]:
#creating order year
df["order_year"] = df["Order Date"].dt.year

In [35]:
#creating order month
df["order_month"] = df["Order Date"].dt.month_name()

In [36]:
#create shipping dates
df["shipping_days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [37]:
#create profit margin
df.groupby("Category")["Sales"].sum()

Category
Furniture          741999.98
Office Supplies    719046.99
Technology         836154.10
Name: Sales, dtype: float64

In [31]:
print(df['Order Date'].head(10))

0    08-11-2016
1    08-11-2016
2    12-06-2016
3    11-10-2015
4    11-10-2015
5    09-06-2014
6    09-06-2014
7    09-06-2014
8    09-06-2014
9    09-06-2014
Name: Order Date, dtype: str

In [32]:
import pandas as pd

df['Order Date'] = pd.to_datetime(
    df['Order Date'],
    format='%d-%m-%Y'
)

df['Ship Date'] = pd.to_datetime(
    df['Ship Date'],
    format='%d-%m-%Y'
)

In [38]:
#Who are the top customers by sales?
df.groupby('Customer Name')['Sales'].sum()\
.sort_values(ascending=False)\
.head(10)

Customer Name
Sean Miller           25043.07
Tamara Chand          19052.22
Raymond Buch          15117.35
Tom Ashbrook          14595.62
Adrian Barton         14473.57
Ken Lonsdale          14175.23
Sanjit Chand          14142.34
Hunter Lopez          12873.30
Sanjit Engle          12209.44
Christopher Conant    12129.08
Name: Sales, dtype: float64

In [39]:
#Which products generate the most revenue?
df.groupby('Product Name')['Sales'].sum()\
.sort_values(ascending=False)\
.head(10)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.83
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.38
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.48
HON 5400 Series Task Chairs for Big and Tall                                   21870.57
GBC DocuBind TL300 Electric Binding System                                     19823.48
GBC Ibimaster 500 Manual ProClick Binding System                               19024.50
Hewlett Packard LaserJet 3310 Copier                                           18839.68
HP Designjet T520 Inkjet Large Format Printer / 24" Color                      18374.90
GBC DocuBind P400 Electric Binding System                                      17965.07
High Speed Automatic Electric Letter Opener                                    17030.31
Name: Sales, dtype: float64

In [40]:
#Do discounts affect profit?
df.groupby('Discount')['Profit'].mean()

Discount
0.00     66.900350
0.10     96.678404
0.15     39.931923
0.20     34.141241
0.30     49.278238
0.32     88.561481
0.40    138.440291
0.45    226.647273
0.50    310.704697
0.60     43.077101
0.70     95.874306
0.80    101.797100
Name: Profit, dtype: float64

In [41]:
#Which products generate losses?
df.groupby('Product Name')['Profit'].sum()\
.sort_values()\
.head(10)

Product Name
Belkin OmniView SE Rackmount Kit                                           0.00
Alliance Big Bands Rubber Bands, 12/Pack                                   0.00
Letter Slitter                                                             0.30
Sony 8GB Class 10 Micro SDHC R40 Memory Card                               0.34
Alliance Rubber Bands                                                      0.54
Brites Rubber Bands, 1 1/2 oz. Box                                         0.91
Newell 337                                                                 1.18
Sanitaire Vibra Groomer IR Commercial Upright Vacuum, Replacement Belts    1.30
SanDisk Cruzer 8 GB USB Flash Drive                                        1.36
Bagged Rubber Bands                                                        1.50
Name: Profit, dtype: float64

In [42]:
#Which states generate the most sales?
df.groupby('State')['Sales'].sum()\
.sort_values(ascending=False)\
.head(10)

State
California      457687.68
New York        310876.20
Texas           170187.98
Washington      138641.29
Pennsylvania    116512.02
Florida          89473.73
Illinois         80166.16
Ohio             78258.21
Michigan         76269.61
Virginia         70636.72
Name: Sales, dtype: float64

In [43]:
#Which cities are most profitable?
df.groupby('City')['Profit'].sum()\
.sort_values(ascending=False)\
.head(10)

City
New York City    69969.18
Los Angeles      32781.64
Seattle          29926.47
Philadelphia     25343.93
San Francisco    20190.99
Houston          19417.34
Chicago          15586.77
Detroit          13181.79
Springfield      12537.19
Newark           12147.39
Name: Profit, dtype: float64

In [44]:
#customers.csv
customers = df[
[
'Customer ID',
'Customer Name',
'Segment'
]
].drop_duplicates()

In [49]:
#products.csv
products = df[
[
'Product ID',
'Category',
'Sub/Category',
'Product Name'
]
].drop_duplicates()

In [50]:
#orders.csv
orders = df[
[
'Row ID',
'Order ID',
'Order Date',
'Ship Date',
'Ship Mode',
'Customer ID',
'Product ID',
'Sales',
'Quantity',
'Discount',
'Profit',
'Country',
'City',
'State',
'Postal Code',
'Region'
]
]

In [51]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.50)
Requirement already satisfied: psycopg2-binary in C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:1234@localhost:5432/superstore_db"
)

In [55]:
customers.head()

products.head()

orders.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Product ID,Sales,Quantity,Discount,Profit,Country,City,State,Postal Code,Region
0,1,CA/2016/152156,2016-11-08,2016-11-11,Second Class,CG/12520,FUR/BO/10001798,261.96,2,0.00,41.91,United States,Henderson,Kentucky,42420,South
1,2,CA/2016/152156,2016-11-08,2016-11-11,Second Class,CG/12520,FUR/CH/10000454,731.94,3,0.00,219.58,United States,Henderson,Kentucky,42420,South
2,3,CA/2016/138688,2016-06-12,2016-06-16,Second Class,DV/13045,OFF/LA/10000240,14.62,2,0.00,6.87,United States,Los Angeles,California,90036,West
3,4,US/2015/108966,2015-10-11,2015-10-18,Standard Class,SO/20335,FUR/TA/10000577,957.58,5,0.45,383.03,United States,Fort Lauderdale,Florida,33311,South
4,5,US/2015/108966,2015-10-11,2015-10-18,Standard Class,SO/20335,OFF/ST/10000760,22.37,2,0.20,2.52,United States,Fort Lauderdale,Florida,33311,South

In [56]:
customers.to_sql(
    'customers',
    engine,
    if_exists='replace',
    index=False
)

793

In [57]:
products.to_sql(
    'products',
    engine,
    if_exists='replace',
    index=False
)

894

In [58]:
orders.to_sql(
    'orders',
    engine,
    if_exists='replace',
    index=False
)

994

In [59]:
products['Product ID'].duplicated().sum()

np.int64(32)

In [60]:
products[products['Product ID'].duplicated(keep=False)]\
.sort_values('Product ID')

,Product ID,Category,Sub/Category,Product Name
2471,FUR/BO/10002213,Furniture,Bookcases,"Sauder Forest Hills Library, Woodland Oak Finish"
2115,FUR/BO/10002213,Furniture,Bookcases,DMI Eclipse Executive Suite Bookcases
66,FUR/CH/10001146,Furniture,Chairs,"Global Value Mid/Back Manager's Chair, Gray"
128,FUR/CH/10001146,Furniture,Chairs,"Global Task Chair, Black"
1459,FUR/FU/10001473,Furniture,Furnishings,DAX Wood Document Frame
...,...,...,...,...
1219,TEC/PH/10002200,Technology,Phones,Samsung Galaxy Note 2
2596,TEC/PH/10002310,Technology,Phones,Plantronics Calisto P620/M USB Wireless Speake...
1378,TEC/PH/10002310,Technology,Phones,Panasonic KX T7731/B Digital phone
922,TEC/PH/10004531,Technology,Phones,OtterBox Commuter Series Case / iPhone 5 & 5s
2713,TEC/PH/10004531,Technology,Phones,AT&T CL2909

In [61]:

products = products.drop_duplicates(
    subset=['Product ID']
)

In [62]:
products['Product ID'].duplicated().sum()

np.int64(0)

In [63]:
products.to_sql(
    'products',
    engine,
    if_exists='replace',
    index=False
)

862